name: 1.1$(rev:.r) # build numbering format

trigger: none

resources:
  pipelines:
    - pipeline: release-pip # Name of the pipeline resource
      source: 01-JestTest-Continuous-Integration # Name of the pipeline referenced by the pipeline resource
      trigger:
        branches:
          - refs/heads/main^

variables:
- group: Jest-Test
- name: buildVersion
  ${{ if eq( variables['Build.SourceBranchName'], 'main' ) }}:
    value:  $(Build.BuildNumber)
  ${{ if ne( variables['Build.SourceBranchName'], 'main' ) }}:
    value: ${{ format('{0}-beta', '$(Build.BuildNumber)') }}

pool:
  name: Azure Pipelines
  vmImage: "windows-latest"
  demands: npm

steps:
  - script: |
      echo "Version: $(buildVersion)"
      echo "Pat: $(VscePublishToken)"
    displayName: "Print version"

  - task: Npm@1
    displayName: "NPM CI"
    inputs:
      command: custom
      verbose: false
      customCommand: ci

  - task: Npm@1
    displayName: "Git Clean"
    inputs:
      command: custom
      verbose: false
      customCommand: "run ci:git-clean"

  - task: Npm@1
    displayName: "Git Config"
    inputs:
      command: custom
      verbose: false
      customCommand: "run ci:git-config"

  - task: Npm@1
    displayName: "Update version"
    inputs:
      command: custom
      verbose: false
      customCommand: "version $(buildVersion)"

  - task: Npm@1
    displayName: "Publish"
    inputs:
      command: custom
      verbose: false
      customCommand: "run ci:vsce-publish -- -p $(VscePublishToken)"
